
services:
  app:
    build:
      # context: .
      dockerfile_inline: |
        FROM node:20
        WORKDIR /app
        RUN npm install -g pnpm
        COPY tsconfig.json package.json pnpm-lock.yaml server vrf /app
        RUN pnpm install
        EXPOSE 8282
        CMD pnpm run start:dev
    ports:
      - 8282:8282
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USERNAME=lootbox_user
      - DATABASE_PASSWORD=lootbox_passwd01
      - DATABASE_PORT=5432
      - DATABASE_DBNAME=lootbox_db
      - DATABASE_SYNCHRONIZE=true
      - DATABASE_URL='postgresql://lootbox_user:lootbox_passwd01@localhost:5432/lootbox_db'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    # command: pnpm run start:dev
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
  db:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=lootbox_user
      - POSTGRES_PASSWORD=lootbox_passwd01
      - POSTGRES_DB=lootbox_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "7654:5432"

volumes:
  db_data: